apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: colosseum-snacks
  name: colosseum-snacks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colosseum-snacks
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: colosseum-snacks
    spec:
      containers:
        - image: johnhunsley/springboot-mongo-kubernetes
          name: colosseum-snacks
          env:
            - name: SPRING_APPLICATION_PROPERTIES
              valueFrom:
                configMapKeyRef:
                  name: colosseum-snacks
                  key: application.properties
status: {}
