apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  annotations:
    kubernetes.io/service-account.name: default
# username mongdadmin password secret
data:
  password: cGFzc3dvcmQxMjM=
  username: YWRtaW51c2Vy