apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo

spec:
  selector:
    matchLabels:
      service: mongo
  replicas: 1
  template:
    metadata:
      labels:
        service: mongo
      name: mongo
    spec:
      containers:
        - args:
            - mongod
          image: mongo:latest
          name: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
